#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2015, OpenNebula Project (OpenNebula.org), C12G Labs        #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #

if [ -z "${ONE_LOCATION}" ]; then
    LIB_LOCATION=/usr/lib/one
else
    LIB_LOCATION=$ONE_LOCATION/lib
fi

. $LIB_LOCATION/sh/scripts_common.sh

DRIVER_PATH=$(dirname $0)
source ${DRIVER_PATH}/../libfs.sh
source ${DRIVER_PATH}/emc.conf
source ${DRIVER_PATH}/func.sh

# -------- Get datastore arguments from OpenNebula core ------------

DRV_ACTION=$1
ID=$2

XPATH="${DRIVER_PATH}/../xpath.rb -b $DRV_ACTION"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <($XPATH     /DS_DRIVER_ACTION_DATA/DATASTORE/BASE_PATH \
		    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/CLI_HOSTNAME \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/CLI_USER \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/CLI_PASSWORD \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/BLOCK_SIZE \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/RAID_GROUP_ID \
                    /DS_DRIVER_ACTION_DATA/DATASTORE/TEMPLATE/RAID_GROUP_RAIDLEVEL \
                    /DS_DRIVER_ACTION_DATA/IMAGE/FSTYPE \
                    /DS_DRIVER_ACTION_DATA/IMAGE/SIZE)

BASE_PATH="${XPATH_ELEMENTS[j++]}"
CLI_HOSTNAME="${XPATH_ELEMENTS[j++]}"
CLI_USER="${XPATH_ELEMENTS[j++]}"
CLI_PASSWORD="${XPATH_ELEMENTS[j++]}"
BLOCK_SIZE="${XPATH_ELEMENTS[j++]:-$BLOCK_SIZE}"
RAID_GROUP_ID="${XPATH_ELEMENTS[j++]}"
RAID_GROUP_RAIDLEVEL="${XPATH_ELEMENTS[j++]}"
FSTYPE="${XPATH_ELEMENTS[j++]}"
SIZE="${XPATH_ELEMENTS[j++]:-0}"

NAVISECCLI="/opt/Navisphere/bin/naviseccli -User $CLI_USER -Password $CLI_PASSWORD -Address $CLI_HOSTNAME -Scope 0 "

# Semaphor - LOCK 
semaphor_on
echo $ID >> $LOCK

# 1. Find empty LUN id
CMD="$NAVISECCLI getlun | awk '/^Name/{print \$3}' | sort -n | awk 'BEGIN{l=10}{if(\$1 > 10){if( l+1 < \$1){exit} l=\$1} }END{print l+1}'"
log "$CMD"
LUN_ID=`echo $CMD | sh`
#TODO: Max limit

# 2. Find about SPx LUN provisioning
CMD="$NAVISECCLI getlun | awk -F: '/Default Owner/{A[\$2]++} END{B=100000; for(i in A){if(A[i]<B){C=i;B=A[i]}};print C}' | sed -e 's/ //g'"
log "$CMD"
SP=`echo $CMD | sh`

# Protection about removing current LUNs
if [ $LUN_ID -lt 2 ]; then
   exit 1;
fi

# 3. bind new LUN
CMD="$NAVISECCLI bind $RAID_GROUP_RAIDLEVEL $LUN_ID -rg $RAID_GROUP_ID -sq mb -cap $SIZE -sp ${SP: -1}"
log "$CMD"
exec_and_log "$CMD" "Error creating new LUN"

# Return Disk identifier
log "Requested space allocated as $LUN_ID"
echo $LUN_ID

# Semaphor - UNLOCK
semaphor_off $LUN_ID


# 4. Format disk to specified format

log "Formatting as $FSTYPE ..."
# Format is not specified
if [ "$FSTYPE" = "save_as" ]; then
    exit 0
fi

exit 0
# ------------ Create the image to the repository ------------


# Connect LUN to host
log "Connecting $LUN_ID to $HOST"
assign_image_to_host $LUN_ID `hostname`
DEV=$(create_block_device $LUN_ID)

# Format
MKFS_CMD="$SUDO $(mkfs_command $DEV $FSTYPE)"

exec_and_log "$MKFS_CMD" \
    "Error make $FSTYPE filesystem on $DEV"

# Unconnect LUN from host
log "Unconnecting $LUN_ID from $HOST"
drop_block_device $LUN_ID
unassign_image_from_host $LUN_ID `hostname`



