#!/bin/bash

# -------------------------------------------------------------------------- #
# Copyright 2002-2015, OpenNebula Project, OpenNebula Systems                #
#                                                                            #
# Licensed under the Apache License, Version 2.0 (the "License"); you may    #
# not use this file except in compliance with the License. You may obtain    #
# a copy of the License at                                                   #
#                                                                            #
# http://www.apache.org/licenses/LICENSE-2.0                                 #
#                                                                            #
# Unless required by applicable law or agreed to in writing, software        #
# distributed under the License is distributed on an "AS IS" BASIS,          #
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   #
# See the License for the specific language governing permissions and        #
# limitations under the License.                                             #
#--------------------------------------------------------------------------- #


SRC=$1
DST=$2
SNAP=$3
VMID=$4
DSID=$5

if [ -z "${ONE_LOCATION}" ]; then
    TMCOMMON=/var/lib/one/remotes/tm/tm_common.sh
else
    TMCOMMON=$ONE_LOCATION/var/remotes/tm/tm_common.sh
fi

. $TMCOMMON

DRIVER_PATH=$(dirname $0)


#-------------------------------------------------------------------------------
# Set dst path and dir
#-------------------------------------------------------------------------------

SRC_HOST=`arg_host $SRC`
SRC_PATH=`arg_path $SRC`
DST_PATH=`arg_path $DST`

DST_HOST=`arg_host $DST`
DST_DIR=`dirname $DST_PATH`

#-------------------------------------------------------------------------------
# Get Datastore information for communication with EMC controller
#-------------------------------------------------------------------------------

XPATH="${DRIVER_PATH}/../../datastore/xpath.rb --stdin"

unset i j XPATH_ELEMENTS

while IFS= read -r -d '' element; do
    XPATH_ELEMENTS[i++]="$element"
done < <(onedatastore show -x $DSID| $XPATH \
                    /DATASTORE/TEMPLATE/CLI_HOSTNAME \
                    /DATASTORE/TEMPLATE/CLI_USER \
                    /DATASTORE/TEMPLATE/CLI_PASSWORD \
                    /DATASTORE/TEMPLATE/BLOCK_SIZE \
                    /DATASTORE/TEMPLATE/RAID_GROUP_ID \
                    /DATASTORE/TEMPLATE/RAID_GROUP_RAIDLEVEL)

CLI_HOSTNAME="${XPATH_ELEMENTS[j++]}"
CLI_USER="${XPATH_ELEMENTS[j++]}"
CLI_PASSWORD="${XPATH_ELEMENTS[j++]}"
BLOCK_SIZE="${XPATH_ELEMENTS[j++]:-$BLOCK_SIZE}"
RAID_GROUP_ID="${XPATH_ELEMENTS[j++]}"
RAID_GROUP_RAIDLEVEL="${XPATH_ELEMENTS[j++]}"

. $DRIVER_PATH/../../datastore/emc/func.sh

#-------------------------------------------------------------------------------
# Get information about Image size and generate a new LUN ID
#-------------------------------------------------------------------------------

while IFS= read -r -d '' element; do
        XPATH_ELEMENTS[i++]="$element"
        done < <(onevm show -x $VMID| $XPATH  \
                            /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/SIZE \
                            /VM/TEMPLATE/DISK[DISK_ID=$DISK_ID]/ORIGINAL_SIZE)

SIZE="${XPATH_ELEMENTS[j++]}"
ORIGINAL_SIZE="${XPATH_ELEMENTS[j++]}"

#-------------------------------------------------------------------------------
# Assign LUN to Host
#-------------------------------------------------------------------------------


DST_PATH="${SRC_PATH}.${DST}"

assign_image_to_host $DST $SRC_HOST

SAVEAS_CMD=$(cat <<EOF
    set -e
    source /var/lib/one/remotes/datastore/emc/func.sh
    create_block_device $DST $DST_PATH
    nice -n 19 dd if=$SRC_PATH of=$DST_PATH bs=64k > /dev/null 2>&1 || echo "Error in DD"
    rm $DST_PATH
    drop_block_device $DST
EOF
)

ssh_exec_and_log "$SRC_HOST" "$SAVEAS_CMD" \
        "Error saving $1 -> LUN:$DST"

unassign_image_from_host $DST $SRC_HOST

exit 0
